In [1]:
import tensorflow as tf

x + y if x > y, and x - y otherwise.

In [16]:

x = tf.random_uniform([],-1,1)
y = tf.random_uniform([],-1,1)
out = tf.cond(tf.greater(x,y),lambda:tf.add(x,y),lambda:tf.sub(x,y))
with tf.Session() as sess:
    print sess.run([out,x,y])

[-0.14508963, 0.17024755, 0.31533718]


x + y if x < y, x - y if x > y, 0 otherwise.

In [21]:
x = tf.random_uniform([],-1,1)
y = tf.random_uniform([],-1,1)
out = tf.case({tf.less(x,y):lambda:tf.add(x,y),tf.greater(x,y):lambda:tf.sub(x,y)},default=lambda:tf.constant(0.0),exclusive=True)
with tf.Session() as sess:
    print sess.run([out,x,y])

[0.56042695, 0.16860509, 0.39182186]


Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
and y as a tensor of zeros with the same shape as x.
Return a boolean tensor that yields Trues if x equals y element-wise.

In [27]:
x = tf.constant([[0,-2,-1],[0,1,2]])
y = tf.zeros_like(x)
out = tf.equal(x,y)
with tf.Session() as sess:
    print sess.run([out,x,y])

[array([[ True, False, False],
       [ True, False, False]], dtype=bool), array([[ 0, -2, -1],
       [ 0,  1,  2]], dtype=int32), array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)]


 [29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858].
Get the indices of elements in x whose values are greater than 30.
Hint: Use tf.where().
Then extract elements whose values are greater than 30.

In [32]:
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
30.97266006,  26.67541885,  38.08450317,  20.74983215,
34.94445419,  34.45999146,  29.06485367,  36.01657104,
27.88236427,  20.56035233,  30.20379066,  29.51215172,
33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(x>30)
result = tf.gather(x,indices)
with tf.Session() as sess:
    print sess.run(result)

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,2, ..., 6

In [34]:
values = tf.range(1,7,1)
out = tf.diag(values)
with tf.Session() as sess:
    print sess.run(out)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


Create a random 2-d tensor of size 10 x 10 from any distribution.
Calculate its determinant.

In [39]:
matrix = tf.random_uniform([10,10],-1,1)
out = tf.matrix_determinant(matrix)
with tf.Session() as sess:
    print sess.run(out)

-1.18073


Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
Return the unique elements in x

In [40]:
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
unique_values,indices = tf.unique(x)
with tf.Session() as sess:
    print sess.run(unique_values)

[ 5  2  3 10  6  4  1  0  9]


Create two tensors x and y of shape 300 from any normal distribution,
as long as they are from the same distribution.
Use tf.less() and tf.select() to return:
- The mean squared error of (x - y) if the average of all elements in (x - y)
  is negative, or
- The sum of absolute value of all elements in the tensor (x - y) otherwise.

In [50]:
# x = tf.constant([1,2,3,4])
# y = tf.constant([1,2,51,41])
x = tf.random_normal([300])
y = tf.random_normal([300])
average = tf.reduce_mean(x-y)
condition = tf.less(average,0)
mean_sq_error = tf.reduce_mean(tf.squared_difference(x,y))
# mean_sq_error = tf.reduce_mean(tf.square(x-y))
sum_of_abso = tf.reduce_sum(tf.abs(x-1))
out = tf.select(condition,mean_sq_error,sum_of_abso)
with tf.Session() as sess:
    print sess.run(out)

1.80022
